### ISSUE TITLE
Reporting to specific dispatcher within try block is not reported later

### ISSUE THREAD

**Issue by abeverley** [markov2/perl5-Log-Report#6]
If a message is sent to a specific dispatcher within a try{} block, then if the messages are captured and reported later, that message is not sent to the dispatcher later. The following code demonstrates the problem:

```
dispatcher SYSLOG => 'syslog';

try {
    report {to=>'syslog'}, WARNING => "Foobar";
} hide => 'ALL';

$@->reportAll(is_fatal => 0); # "Foobar" message is not sent to syslog
```
This seems to be because when the message is dispatched by ```reportAll``` using ```report```, only the Try dispatcher is available, not the other dispatchers, so nothing happens at [this line](https://github.com/markov2/perl5-Log-Report/blob/21b09b21f04a27f87c5c7f57a34ff3036324fc5d/lib/Log/Report.pm#L247).

Is this a bug or a feature? I know I can dispatch to a different dispatcher with ```reportAll```, but this isn't possible in my case as there are different messages in the try block and I only want to send a specific one to another dispatcher.

**Comment by markov2** [comment]
This is situation which was not considered.  What would you expect to happen:

1. Let try() only catch messages which are not explicitly targeted for a specific dispatchers
2. Let try() catch everything, and reportAll() find the specific destination

I lean to the second.  Should reportAll() get an option to overrule the destination?

By the way, your try block can also be written as
```perl
try { warning "Foobar", _to => 'syslog' }
```

**Comment by abeverley** [comment]
Thanks for the quick reply Mark. 

>     2\. Let try() catch everything, and reportAll() find the specific destination

Definitely this. The reason (in my case) is that the try block is very far back in the code and one might not even realise it is there. So it is important for the message to still be caught and dispatched.

FWIW, the try block in this case is [this one](https://github.com/markov2/perl5-Log-Report/blob/21b09b21f04a27f87c5c7f57a34ff3036324fc5d/lib/Dancer2/Plugin/LogReport.pm#L228)

>  Should reportAll() get an option to overrule the destination?

Good question. I think the answer is "yes".

**Comment by markov2** [comment]
I have reworked the docs of ::Try, because it is confusing.  Now, I think I understand it myself ;-)

The fix for the first issue is quite simple.  In manual patch mode to Log/Report.pm around line 300:
```perl
    if(my $to = $message->to)
    {   @disp = grep $_->name eq $to, @disp;
        push @disp, $nested_tries[-1] if $nested_tries[-1] && $to ne 'try';
        @disp or return;
    }
```

The 'to' option from report() will now remove the 'to' selector of a message when specified:
```perl
   report { to => 'out2' } ERROR => _ _x"Help!", _to => 'out1';
   $@->reportAll(to => 'out2');   # similar redirection, because calls report() internally
```
The exception message will forget it had a specific destination.  This is what people expect to happen.

Released to CPAN as 1.30

**Comment by abeverley** [comment]
Thanks Mark, but I'm not sure the original issue is fixed. Here is an MWE:

```
use Log::Report;

report {to=>'default'}, WARNING => "Foobar1";

try {
    report {to=>'default'}, WARNING => "Foobar2";
} hide => 'ALL';

$@->reportAll(is_fatal => 0);
```
Or even simpler (I think):
```
use Log::Report;

report {to=>'default'}, WARNING => "Foobar1";

try {
    report {to=>'default'}, WARNING => "Foobar2";
};
```

Received output:
```
warning: Foobar1
```
Expected output: 
```
warning: Foobar1
warning: Foobar2
```

The problem seems to be at [this line](https://github.com/markov2/perl5-Log-Report/blob/54a3d43d1a3c0d4e8536732642a34b0eac85a645/lib/Log/Report.pm#L257). When within a try block, the only dispatcher is a Try dispatcher, so the message is discarded at that point.

**Comment by markov2** [comment]
* Andy Beverley (notifications@github.com) [210115 12:26]:
> Thanks Mark, but I'm not sure the original issue is fixed. Here is an MWE:

New release: 1.31
-- 
               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net

**Comment by abeverley** [comment]
Brilliant, all works as expected. Many thanks for the prompt response.

**Comment by abeverley** [comment]
Bah, sorry, I didn't test properly, still problems I think.

MWE:
```
dispatcher SYSLOG => 'syslog';
dispatcher PERL => 'default';

try {
    report {to=>'syslog'}, WARNING => "Foobar";
} hide => 'ALL';

$@->reportAll(is_fatal => 0);
```
I would expect the above to log to SYSLOG but not STDERR. However, it appears at both.

This fixes it. Does it cause other problems?

```
@@ -131,7 +131,7 @@ sub report($@)
         $message = $lrm->new(_prepend => $text, @_);
     }
 
-    $message->to(undef) if $to;  # overrule destination of message
+    $message->to($to) if $to;  # overrule destination of message
 
     if(my $disp_name = $message->to)
     {   @disp = grep $_->name eq $disp_name, @disp;
```

**Comment by markov2** [comment]
* Andy Beverley (notifications@github.com) [210115 18:02]:
```perl
dispatcher SYSLOG => 'syslog';
dispatcher PERL => 'default';

try {
    report {to=>'syslog'}, WARNING => "Foobar";
} hide => 'ALL';

$@->reportAll(is_fatal => 0);
```
> I would expect the above to log to SYSLOG but not STDERR. However, it appears at both.

Actually, this is by design.  At reportAll(), you want to have an idea
where the messages are going to without knowing what the messages are.
In the physics interpretation of the term "locallity".  In the context
of $@, you have two active dispatchers.

> -    $message->to(undef) if $to;  # overrule destination of message
> +    $message->to($to) if $to;  # overrule destination of message

No, that won't produce what you want.  Try like this:

   $@->reportAll(to => 'syslog', is_fatal => 0);

When it gets more complicated, you may add class'es to your messages, and
forward exceptions based on those.  Does that suffice?

MarkOv

**Comment by abeverley** [comment]
On Fri, 15 Jan 2021 12:12:50 -0800 Mark Overmeer wrote:
> > I would expect the above to log to SYSLOG but not STDERR. However,
> > it appears at both.
> 
> Actually, this is by design.  At reportAll(), you want to have an idea
> where the messages are going to without knowing what the messages are.

Ah, that's a shame. I would have expected reportAll() to report the
messages the same as if they were reported directly, and then only
changed if overridden in the reportAll() call itself.

> > -    $message->to(undef) if $to;  # overrule destination of message
> > +    $message->to($to) if $to;  # overrule destination of message
> 
> No, that won't produce what you want.

When I tested it, it seemed to do what I want. Are there other side
effects?

> Try like this:
>    $@->reportAll(to => 'syslog', is_fatal => 0);

That doesn't work unfortunately. I have only some messages in the block
that I want to direct, and in any case when report() is called in the
function in question it may not know it's within a try{} block. FWIW,
it is this line, which could be called anywhere within the application:

https://github.com/ctrlo/GADS/blob/654528dd8d53942d2707c98a4c31c4af1ebcf014/public/dispatch.fcgi#L17

I want to make sure that the above report() is only going to syslog,
whenever it is called in the application. Sometimes it is in a try
block, sometimes not.

> When it gets more complicated, you may add class'es to your messages, and
> forward exceptions based on those.  Does that suffice?

Not sure, I will try. It might work, if I override the current
dispatcher.

Is there a reason not to have reportAll() report the messages as per
the message defaults? That would seem to be expected behaviour to me,
and then only change if parameters are passed to reportAll(). I would
prefer this if possible.

Thanks!

Andy

**Comment by abeverley** [comment]
Okay, I used a class (https://github.com/ctrlo/GADS/commit/8e26170). Turned out that there is already a suitable class built into Dancer2::Plugin::LogReport.

Nonetheless, when calling reportAll(), I still think I would expect messages to go to their defined destination when no destination parameter was passed.

**Comment by markov2** [comment]
* Andy Beverley (notifications@github.com) [210115 22:16]:
> On Fri, 15 Jan 2021 12:12:50 -0800 Mark Overmeer wrote:
> > > I would expect the above to log to SYSLOG but not STDERR. However,
> > > it appears at both.
> > 
> > Actually, this is by design.  At reportAll(), you want to have an idea
> > where the messages are going to without knowing what the messages are.
> 
> Ah, that's a shame. I would have expected reportAll() to report the
> messages the same as if they were reported directly, and then only
> changed if overridden in the reportAll() call itself.

The ability to direct something to a specific dispatcher is a feature
which should be avoided.  The concept of LogReport is that messages
only get directed to loggers in the main program: other corners of
the program should not know which dispatchers are active.  So, be aware
you you a feature which breaks this abstraction.

In "normal" exception systems, you get code like this:

   try { EXCEPTION::MISSING::VALUE->new(...)->throw }
   catch EXCEPTION::MISSING::VALUE { syslog 'warning', ... }

This would be in LogReport

   try { warning 'Foobar', _class => 'missing' };
   foreach my $e ($@->exceptions)
   {   $e->throw(to => 'syslog') if $e->inClass('missing');
   }

It may be useful to add this syntax:

   $_->throw(to => 'syslog')
       for $@->exceptions(class => 'missing');

The 'class' is a tagging mechanism: each exception can have more than
one.  It's more flexible than the usual exception classes, which are
in an strictly ordered hierarchy of inheritance.

So, applied to your situation, you would only mark the items you
would like to get into syslog into logical groups: the redirection
after the try block would decide where those groups go.

You could change this GADS/public/dispatch.fcgi

 - $SIG{__WARN__} = sub { GADS::warning(@_) };
 + $SIG{__WARN__} = sub { GADS::warning("@_", _class => 'perl_warn') };

> > > -    $message->to(undef) if $to;  # overrule destination of message
> > > +    $message->to($to) if $to;  # overrule destination of message
> > 
> > No, that won't produce what you want.
> 
> When I tested it, it seemed to do what I want. Are there other side
> effects?

I had to think very deep why I wrote it ;-)   There are a few
situation where this can happen, I think:

   my $e = $@->wasFatal;
   $e->throw(to => 'stdout');
   $e->throw;

The latter throw() [which internally uses report()] now also only
sends only to 'stdout', because $msg->to() has modified the
destination as hidden side-effect.

The C<undef> has a different purpose: whatever the destination of the
message was, we will overrule it when $to is set.  Also a side-effect,
but better to defend (in my malformed, circular, self-contradictionary,
alcohol affected brain)

> > Try like this:
> >    $@->reportAll(to => 'syslog', is_fatal => 0);
> 
> That doesn't work unfortunately. I have only some messages in the block
> that I want to direct, and in any case when report() is called in
> the function in question it may not know it's within a try{} block.

You do not have to catch the warnings in that particular try(): for
some reason you wanted to catch and rethrow them.

> Is there a reason not to have reportAll() report the messages as per
> the message defaults? That would seem to be expected behaviour to me,
> and then only change if parameters are passed to reportAll(). I would
> prefer this if possible.

I had to think too deep about this.
Removing this new line would achieve that:
   $message->to(undef) if $to;  # overrule destination of message

-- 
Regards,
               MarkOv

------------------------------------------------------------------------
       Mark Overmeer MSc                                MARKOV Solutions
       Mark@Overmeer.net                          solutions@overmeer.net
http://Mark.Overmeer.net                   http://solutions.overmeer.net

**Comment by abeverley** [comment]
> So, applied to your situation, you would only mark the items you
> would like to get into syslog into logical groups: the redirection
> after the try block would decide where those groups go.

Thanks Mark, that's what I did in the end.

> > > > -    $message->to(undef) if $to;  # overrule destination of message
> > > > +    $message->to($to) if $to;  # overrule destination of message
> > > 
> > > No, that won't produce what you want.
> > 
> > When I tested it, it seemed to do what I want. Are there other side
> > effects?
> 
> I had to think very deep why I wrote it ;-)   There are a few
> situation where this can happen, I think:
> 
>    my $e = $@->wasFatal;
>    $e->throw(to => 'stdout');
>    $e->throw;
> 
> The latter throw() [which internally uses report()] now also only
> sends only to 'stdout', because $msg->to() has modified the
> destination as hidden side-effect.
> 
> The C<undef> has a different purpose: whatever the destination of the
> message was, we will overrule it when $to is set.  Also a side-effect,
> but better to defend (in my malformed, circular, self-contradictionary,
> alcohol affected brain)

Ah, okay, I guess in an ideal world both could be done (i.e. throw a
message multiple times and override its destination once only; and set
a default destination on a message). I accept these are edge-cases
though.

> > > Try like this:
> > >    $@->reportAll(to => 'syslog', is_fatal => 0);
> > 
> > That doesn't work unfortunately. I have only some messages in the block
> > that I want to direct, and in any case when report() is called in
> > the function in question it may not know it's within a try{} block.
> 
> You do not have to catch the warnings in that particular try(): for
> some reason you wanted to catch and rethrow them.

It was an old problem we had. There was a situation where messages were
reported out of order if they weren't all caught and then reported in
one go. I forget the exact details; it was to do with having multiple
nested try blocks. What happened was that a trace message was emitted
after a fatal message, and the trace message was the one stored in $@.

> > Is there a reason not to have reportAll() report the messages as per
> > the message defaults? That would seem to be expected behaviour to me,
> > and then only change if parameters are passed to reportAll(). I would
> > prefer this if possible.
> 
> I had to think too deep about this.
> Removing this new line would achieve that:
>    $message->to(undef) if $to;  # overrule destination of message

Like I say, it would be nice to have all possibilities without
side-effects. But I don't know the internal code well enough.

So, now that I have implemented the use of using classes I am content
with the code as it is, just a nice to have really.

Many thanks,

Andy
